name: Document Repository

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  Document-Repository:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve git dependencies
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm i -g documentation


      - name: Set up Github
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email ""
          git config pull.rebase false  # merge
          git config pull.ff only       # fast-forward only
          
          git fetch
          git checkout -b gh-pages
          git pull origin gh-pages
          rm -rf ./* # Remove all files from the old build, so we don't have any conflicts
          git add .
          git commit -m "Clean up old build"
          git push origin gh-pages
          git merge main
          git commit -m "Merge main into gh-pages"

      - name: Run documentation
        run: sh ./scripts/docs.sh

      # - name: Deploy to GitHub Pages 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.1
      #   with:
      #     branch: gh-pages
      #     folder: ./

      - name: Deploy to GitHub Pages 🚀
        run: |
          git add .
          git commit -m "Update docs"
          git push origin gh-pages