name: Document Repository

on:
  push:
    branches: ["docs"]
  pull_request:
    branches: ["docs"]

permissions:
  contents: read

jobs:
  Document-Repository:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve git dependencies
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm i -g documentation

      - name: Run documentation
        run: sh ./scripts/docs.sh

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs