name: Document Repository

on:
  push:
    branches: ["docs"]
  pull_request:
    branches: ["docs"]

permissions:
  contents: read

jobs:
  Document-Repository:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm i -g documentation

      - name: Run documentation
        run: sh ./scripts/docs.sh

      - name: Deploy to GitHub Pages 🚀
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email ""
          git add .
          git commit -m "Deploy documentation"
          git push origin HEAD:gh-pages --force # force push to the docs branch