---
name: 'Merge Template'


on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  merge-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # with:
        #   fetch-depth: 0
        #   ref: ${{ github.head_ref }}

      - name: 'Setup ssh-agent'
        uses: 'webfactory/ssh-agent@v0.5.0'
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}


      # loop through templates, merge main of this into tsaxking/template-${ templateName }

      - name: Merge Template
        run: |
          git config --local user.name "Webpack Bot"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # Set list all repositories here:
          for template in budgeting sfz scouting-app tators-dashboard minecraft; do
            echo "Merging template $template"

            # remove origin
            git remote remove origin
            echo "Removed origin"
            # add template as remote
            echo "Adding $template as remote to git@github.com:tsaxking/template-$template.git"
            git remote add origin git@github.com:tsaxking/template-$template.git
            echo "Added $template as remote"

            echo "Switching to new branch template-merge-$template"
            git checkout -b template-merge-$template
            echo "Switched to new branch"
            echo "Merging main into $template"
            git status
            git merge main
            echo "Merged main into $template"

            echo "Pushing to template-merge-$template"
            git push origin --set-upstream template-merge-$template
            echo "Pushed to template-merge-$template"

            echo "Creating PR"
            # create PR
            gh pr create --title "Merge main into $template" --body "This PR was automatically created by the Tators Bot. Please review and merge." --base main --head $template:template-merge-$template
            echo "Created PR"

            echo "Deleting temporary branch template-merge-$template"
            git checkout main
            git branch -D template-merge-$template
            echo "Deleted branch template-merge-$template"
            echo "Done merging template $template"
            done