---
name: 'Merge Template'


on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  merge-template:
    runs-on: ubuntu-latest

    steps:


      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        #   ref: ${{ github.head_ref }}
      

      - name: 'Setup ssh-agent'
        uses: 'webfactory/ssh-agent@v0.5.0'
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}



      # loop through templates, merge main of this into tsaxking/template-${ templateName }

      - name: Merge Template
        run: |
          git config --local user.name "Webpack Bot"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --global core.compression 0

          git checkout main
          # git pull origin main --no-edit
          # git commit --allow-empty -m "trigger-merge"
          # git push origin main


          # Set list all repositories here:
          for template in budgeting sfz scouting-app tators-dashboard minecraft; do
            echo "Merging template $template"

            echo "Switching origin to template-$template"
            git remote remove origin
            git remote add origin git@github.com:tsaxking/template-$template.git
            
            echo "Creating branch template-$template"
            git checkout -b merge-template-$template
            git fetch
            # git pull origin main --no-edit
            git pull origin main --no-edit
            git pull origin merge-template-$template --no-edit

            git rm --cached ./.github/workflows/merge-template.yml
            git commit -m "Remove merge-template.yml"
            
            git status

            # git pull origin main --no-edit
            git push --set-upstream origin merge-template-$template

            echo "Creating a pull request"
            # git checkout main
            # git request-pull main git@github.com:tsaxking/template-$template.git

            echo "Deleting branch template-$template"
            git branch -D merge-template-$template

            echo "Switching origin back to main"
            git remote remove origin
            git remote add origin git@github.com:tsaxking/webpack-template.git
            done