---
name: 'Merge Template'


on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  merge-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # with:
        #   fetch-depth: 0
        #   ref: ${{ github.head_ref }}

      - name: 'Setup ssh-agent'
        uses: 'webfactory/ssh-agent@v0.5.0'
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}


      # loop through templates, merge main of this into tsaxking/template-${ templateName }

      - name: Merge Template
        run: |
          git config --local user.name "Webpack Bot"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # Set list all repositories here:
          for template in budgeting sfz scouting-app tators-dashboard minecraft; do
            echo "Merging template $template"

            echo "Adding remote origin"
            git remote rename origin upstream
            git remote add origin git@github.com:tsaxking/template-$template.git
            git fetch origin

            echo "Merging upstream/main into origin/main"
            git checkout -b merge-template
            git merge upstream/main --no-edit

            echo "Pushing to origin"
            git push origin merge-template --no-thin --force

            echo "Creating pull request"
            git checkout main
            git branch -D merge-template
            gh pr create --fill --base main --head merge-template --title "Merge template $template" --body "Merging template $template"


            echo "Removing remote origin"
            git remote remove origin
            git remote rename upstream origin

            echo "Finished merging template $template"
            done