
name: 'Merge Template'

on:
  push:
    branches:
      - main

jobs:
  merge-template:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        templates: [
          budgeting,
          sfz,
          minecraft,
          scouting-app,
          tators-dashboard
        ]

    steps:
      - name: Retrieve git dependencies
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GITHUB_TOKEN }}

      
      - name: 'Setup ssh-agent'
        uses: 'webfactory/ssh-agent@v0.5.0'
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}

      - name: Send pull-request
        run: |
          echo "Creating variables"
          LATEST_TAG=$(git describe --tags --always --abbrev=0)
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          REPOSITORY="tsaxking/template-${{ matrix.templates }}"
          BRANCH_NAME="chore-update-scripts-to-$LATEST_TAG"
          echo " latest tag: $LATEST_TAG"
          echo " repository: $REPSOITORY"
          echo "     folder: $FOLDER"
          echo "branch name: $BRANCH_NAME"

          echo "deleting workflow files"
          rm -rf .github/workflows

          # Clone the remote repository and change working directory to the
          # folder it was cloned to.
          # echo "Cloning repository"
          # cd ../
          # git clone \
          #   --depth=1 \
          #   --branch=main \
          #   git@github.com:tsaxking/template-${{ matrix.templates }}.git
          # ls -la

          # cd template-${{ matrix.templates }}

          echo "Setting up identity"
          # Setup the committers identity.
          git config --global user.email "taylorking206@u.boisestate.edu"
          git config --global user.name "Webpack Bot"

          echo "Changing remote"
          # Change the remote to the repository we want to push to.
          git remote rm origin
          git remote add origin git@github.com:tsaxking/template-${{ matrix.templates }}.git

          echo "Checking out Branch: $BRANCH_NAME"
          # Create a new feature branch for the changes.
          git checkout -b $BRANCH_NAME

          echo "Committing"
          # Commit the changes and push the feature branch to origin
          git add .
          git commit -m "chore: update scripts to $LATEST_TAG"
          git push origin --set-upstream $BRANCH_NAME