---
name: 'Merge Template'


on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  merge-template:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        #   ref: ${{ github.head_ref }}

      - name: 'Setup ssh-agent'
        uses: 'webfactory/ssh-agent@v0.5.0'
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}


      # loop through templates, merge main of this into tsaxking/template-${ templateName }

      - name: Merge Template
        run: |
          git config --local user.name "Webpack Bot"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --global core.compression 0

          # Set list all repositories here:
          for template in budgeting sfz scouting-app tators-dashboard minecraft; do
            echo "Merging template $template"

            git remote origin add tsaxking/template-$template
            git fetch origin
            git checkout -b $template origin/template-$template
            git merge main
            git push origin $template

            git checkout main
            git branch -D $template

            git remote remove tsaxking/template-$template

            echo "Merged template $template"
            done