
name: 'Merge Template'

on:
  push:
    branches:
      - main

jobs:
  merge-template:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        templates: [
          # budgeting,
          # sfz,
          # minecraft,
          scouting-app #,
          # tators-dashboard
        ]

    steps:
      - name: Retrieve git dependencies
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Checkout everything to get access to the tags
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.GITHUB_TOKEN }}

      
      - name: 'Setup ssh-agent'
        uses: 'webfactory/ssh-agent@v0.5.0'
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}

      - name: Send pull-request
        run: |
          echo "Creating variables"
          LATEST_TAG=$(git describe --tags --always --abbrev=0)
          REPOSITORY="tsaxking/template-${{ matrix.templates }}"
          FOLDER="bin/$REPOSITORY"
          BRANCH_NAME="chore-update-scripts-to-$LATEST_TAG"
          echo " latest tag: $LATEST_TAG"
          echo " repository: $REPSOITORY"
          echo "     folder: $FOLDER"
          echo "branch name: $BRANCH_NAME"

          # Clone the remote repository and change working directory to the
          # folder it was cloned to.
          echo "Cloning repository"
          git clone \
            --depth=1 \
            --branch=main \
            git@github.com:tsaxking/template-${{ matrix.templates }}.git \
            $FOLDER

          echo "Changing directory: $FOLDER"
          cd $FOLDER

          echo "Setting up identity"
          # Setup the committers identity.
          git config user.email "taylorking206@u.boisestate.edu"
          git config user.name "Webpack Bot"

          # echo "Setting up origin"
          # git remote rm origin
          # git remote add origin git@github.com:tsaxking/template-${{ matrix.templates }}.git

          echo "Checking out Branch: $BRANCH_NAME"
          # Create a new feature branch for the changes.
          git checkout -b $BRANCH_NAME

          echo "Copying Files"
          # Update the script files to the latest version.
          cp -R ../../../scripts scripts

          echo "Committing"
          # Commit the changes and push the feature branch to origin
          git add .
          git commit -m "chore: update scripts to $LATEST_TAG"
          git push origin $BRANCH_NAME

          # Store the PAT in a file that can be accessed by the
          # GitHub CLI.
          echo "${{ secrets.GITHUB_TOKEN }}" > token.txt

          # Authorize GitHub CLI for the current repository and
          # create a pull-requests containing the updates.
          # echo "Generating Pull Request"
          # gh auth login --with-token < token.txt
          # gh pr create \
          #   --body "Merging template, this was created by the merge-template.yml workflow. Please review and merge asap as it may have security updates. \n\n\n Auto-generated by [create-pull-request][1]" \
          #   --title "chore: update scripts to $LATEST_TAG" \
          #   --head "$BRANCH_NAME" \
          #   --base "main" \
          #   --repo "git@github.com:tsaxking/template-${{ matrix.templates }}.git"