---
name: 'Merge Template'


on:
  push:
    branches:
      - main

jobs:
  merge-template:
    runs-on: ubuntu-latest

    steps:
      - name: 'Do nothing'
        run: echo "This is a template."

    # Connect to servers and run commands